export const packages = [
  {
    image: "/images/ramadan-banner.jpg",
    name: "কাপল প্যাকেজ",
    description: "কাপল প্যাকেজে পাচ্ছেন দুইজনের জন্য সম্পূর্ণ প্যাকেজ",
    price: 110,
    discountedPrice: 100,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/images/ramadan-banner.jpg",
    name: "সিঙ্গেল প্যাকেজ",
    description: "সিঙ্গেল প্যাকেজে পাচ্ছেন একজনের জন্য সম্পূর্ণ প্যাকেজ",
    price: 60,
    discountedPrice: 50,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
];

export const items = [
  {
    image: "/products/chola.jpg",
    name: "ছোলা",
    description: "সম্পূর্ণ নির্ভেজাল ঘরে তৈরি ছোলা",
    price: 160,
    discountedPrice: 150,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/muri.jpg",
    name: "মুড়ি",
    description: "টাটকা এবং মুচমুচে মুড়ি",
    price: 80,
    discountedPrice: 60,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/ginger-e.png",
    name: "পেঁয়াজি",
    description: "পেয়াজ এবং খেসারি ডালের তৈরি পেঁয়াজি",
    price: 7,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/potato.jpg",
    name: "আলুর চপ",
    description: "মুরগির মাংসের পুর দেওয়া সুস্বাদু আলুর চপ",
    price: 15,
    discountedPrice: 10,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/morich.jpg",
    name: "মরিচের চপ",
    description: "Very Tasty ginger",
    price: 7,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/begun.jpg",
    name: "বেগুনি",
    description: "মচমচে এবং সুস্বাদু বেগুনি",
    price: 6,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/bunia.jpg",
    name: "বুন্দিয়া",
    description: "সম্পূর্ণ ঘরে তৈরি, সুস্বাদু বুন্দিয়া",
    price: 200,
    discountedPrice: 180,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/date.jpg",
    name: "খেজুর",
    description: "মানসম্পন্ন,অথেন্টিক খেজুর",
    price: 10,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/juice.webp",
    name: "লাচ্ছি",
    description: "খাঁটি দুধ এবং দই এর তৈরি সুস্বাদু লাচ্ছি",
    price: 50,
    discountedPrice: 45,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/jilapi.jpg",
    name: "জিলাপি",
    description: "সুস্বাদু ও মুচমুচে জিলাপি",
    price: 200,
    discountedPrice: 180,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/chira-vaja.jpg",
    name: "চিড়া ভাজা",
    description: "টাটকা এবং মুচমুচে চিড়া ভাজা",
    price: 80,
    discountedPrice: 60,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/rosun-chop.jpg",
    name: "রসুনের চপ",
    description: "রসুনের তৈরি সুস্বাদু রসুনের চপ",
    price: 7,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
];
