export const items = [
  {
    image: "/products/chola.jpg",
    name: "ছোলা",
    description: "Very Tasty ginger",
    price: 160,
    discountedPrice: 150,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/muri.jpg",
    name: "মুড়ি",
    description: "Very Tasty ginger",
    price: 80,
    discountedPrice: 60,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/ginger-e.png",
    name: "পেঁয়াজি",
    description: "Very Tasty ginger",
    price: 7,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/potato.jpg",
    name: "আলুর চপ",
    description: "Very Tasty ginger",
    price: 15,
    discountedPrice: 10,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/morich.jpg",
    name: "মরিচের চপ",
    description: "Very Tasty ginger",
    price: 7,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/begun.jpg",
    name: "বেগুনি",
    description: "Very Tasty ginger",
    price: 6,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/bunia.jpg",
    name: "বুন্দিয়া",
    description: "Very Tasty ginger",
    price: 200,
    discountedPrice: 180,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/date.jpg",
    name: "খেজুর",
    description: "Very Tasty ginger",
    price: 10,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/juice.webp",
    name: "লাচ্ছি",
    description: "Very Tasty ginger",
    price: 50,
    discountedPrice: 45,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/jilapi.jpg",
    name: "জিলাপি",
    description: "Very Tasty ginger",
    price: 200,
    discountedPrice: 180,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/chira-vaja.jpg",
    name: "চিড়া ভাজা",
    description: "Very Tasty ginger",
    price: 80,
    discountedPrice: 60,
    step: 0.25,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
  {
    image: "/products/rosun-chop.jpg",
    name: "রসুনের চপ",
    description: "Very Tasty ginger",
    price: 7,
    discountedPrice: 5,
    className: "hover:shadow-2xl transition-shadow duration-300",
  },
];
